<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Test;
use Illuminate\Support\Str;
use Carbon\Carbon;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tests = [
            // TNI Category Tests
            [
                'code' => 'TNI-AD-001',
                'title' => 'Tryout TNI AD - Paket Lengkap 2024',
                'description' => 'Simulasi lengkap tes masuk TNI Angkatan Darat dengan soal-soal terbaru sesuai standar TNI. Mencakup materi Akademik, Psikologi, dan Kesehatan.',
                'category' => 'tni',
                'time_limit' => 120,
                'attempts_allowed' => 3,
                'price' => 75000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(30),
                'registration_deadline' => Carbon::now()->addDays(25),
            ],
            [
                'code' => 'TNI-AU-001',
                'title' => 'Tryout TNI AU - Akademi Angkatan Udara',
                'description' => 'Tes simulasi masuk TNI Angkatan Udara dengan fokus pada kemampuan akademik dan psikotes yang sesuai dengan standar AAU.',
                'category' => 'tni',
                'time_limit' => 150,
                'attempts_allowed' => 2,
                'price' => 85000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(35),
                'registration_deadline' => Carbon::now()->addDays(30),
            ],
            [
                'code' => 'TNI-AL-001',
                'title' => 'Tryout TNI AL - Akademi Angkatan Laut',
                'description' => 'Simulasi tes masuk TNI Angkatan Laut dengan materi yang disesuaikan dengan kurikulum AAL terbaru.',
                'category' => 'tni',
                'time_limit' => 135,
                'attempts_allowed' => 2,
                'price' => 80000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(40),
                'registration_deadline' => Carbon::now()->addDays(35),
            ],
            [
                'code' => 'TNI-FREE-001',
                'title' => 'Tryout TNI - Matematika Dasar (Gratis)',
                'description' => 'Latihan soal matematika dasar untuk persiapan tes TNI. Cocok untuk pemula yang ingin mengasah kemampuan dasar.',
                'category' => 'tni',
                'time_limit' => 60,
                'attempts_allowed' => 5,
                'price' => 0.00,
                'is_active' => true,
                'is_free' => true,
                'show_result' => true,
                'randomize_questions' => false,
                'exam_date' => null,
                'registration_deadline' => null,
            ],

            // POLRI Category Tests
            [
                'code' => 'POLRI-AK-001',
                'title' => 'Tryout POLRI - Akademi Kepolisian 2024',
                'description' => 'Simulasi komprehensif tes masuk POLRI untuk Akademi Kepolisian. Meliputi tes akademik, psikologi, dan wawasan kebangsaan.',
                'category' => 'polri',
                'time_limit' => 180,
                'attempts_allowed' => 2,
                'price' => 90000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(45),
                'registration_deadline' => Carbon::now()->addDays(40),
            ],
            [
                'code' => 'POLRI-PTU-001',
                'title' => 'Tryout POLRI - Bintara PTU',
                'description' => 'Tes simulasi untuk calon Bintara POLRI melalui jalur PTU (Pendidikan Pembentukan Bintara).',
                'category' => 'polri',
                'time_limit' => 120,
                'attempts_allowed' => 3,
                'price' => 65000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(50),
                'registration_deadline' => Carbon::now()->addDays(45),
            ],
            [
                'code' => 'POLRI-TAM-001',
                'title' => 'Tryout POLRI - Tamtama',
                'description' => 'Persiapan tes masuk POLRI untuk jenjang Tamtama dengan materi yang disesuaikan dengan kurikulum terbaru.',
                'category' => 'polri',
                'time_limit' => 90,
                'attempts_allowed' => 3,
                'price' => 55000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(55),
                'registration_deadline' => Carbon::now()->addDays(50),
            ],
            [
                'code' => 'POLRI-FREE-001',
                'title' => 'Tryout POLRI - Wawasan Kebangsaan (Gratis)',
                'description' => 'Latihan soal wawasan kebangsaan untuk persiapan tes POLRI. Materi mencakup Pancasila, UUD 1945, dan NKRI.',
                'category' => 'polri',
                'time_limit' => 45,
                'attempts_allowed' => 10,
                'price' => 0.00,
                'is_active' => true,
                'is_free' => true,
                'show_result' => true,
                'randomize_questions' => false,
                'exam_date' => null,
                'registration_deadline' => null,
            ],

            // Kedinasan Category Tests
            [
                'code' => 'CPNS-SKD-001',
                'title' => 'Tryout CPNS - SKD 2024',
                'description' => 'Tes Seleksi Kompetensi Dasar CPNS lengkap dengan materi TWK, TIU, dan TKP sesuai standar BKN.',
                'category' => 'kedinasan',
                'time_limit' => 100,
                'attempts_allowed' => 3,
                'price' => 0.00,
                'is_active' => true,
                'is_free' => true,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(60),
                'registration_deadline' => Carbon::now()->addDays(55),
            ],
            [
                'code' => 'STAN-PREM-001',
                'title' => 'Tryout STAN - Paket Premium',
                'description' => 'Simulasi tes masuk STAN (Sekolah Tinggi Akuntansi Negara) dengan soal-soal berkualitas tinggi dan pembahasan lengkap.',
                'category' => 'kedinasan',
                'time_limit' => 180,
                'attempts_allowed' => 2,
                'price' => 95000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(65),
                'registration_deadline' => Carbon::now()->addDays(60),
            ],
            [
                'code' => 'STIS-STAT-001',
                'title' => 'Tryout STIS - Statistika',
                'description' => 'Persiapan tes masuk STIS (Sekolah Tinggi Ilmu Statistik) dengan fokus pada matematika dan statistika.',
                'category' => 'kedinasan',
                'time_limit' => 120,
                'attempts_allowed' => 3,
                'price' => 70000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(70),
                'registration_deadline' => Carbon::now()->addDays(65),
            ],
            [
                'code' => 'IPDN-PEMDA-001',
                'title' => 'Tryout IPDN - Institut Pemerintahan Dalam Negeri',
                'description' => 'Simulasi tes masuk IPDN dengan materi akademik dan tes kepribadian sesuai standar institusi.',
                'category' => 'kedinasan',
                'time_limit' => 150,
                'attempts_allowed' => 2,
                'price' => 80000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(75),
                'registration_deadline' => Carbon::now()->addDays(70),
            ],
            [
                'code' => 'KED-FREE-001',
                'title' => 'Tryout Kedinasan - TWK Dasar (Gratis)',
                'description' => 'Latihan soal Tes Wawasan Kebangsaan (TWK) untuk persiapan berbagai tes kedinasan.',
                'category' => 'kedinasan',
                'time_limit' => 60,
                'attempts_allowed' => 5,
                'price' => 0.00,
                'is_active' => true,
                'is_free' => true,
                'show_result' => true,
                'randomize_questions' => false,
                'exam_date' => null,
                'registration_deadline' => null,
            ],
            [
                'code' => 'KED-TIU-001',
                'title' => 'Tryout Kedinasan - TIU (Tes Intelegensia Umum)',
                'description' => 'Fokus pada kemampuan verbal, numerik, dan figural untuk berbagai tes masuk sekolah kedinasan.',
                'category' => 'kedinasan',
                'time_limit' => 90,
                'attempts_allowed' => 4,
                'price' => 45000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => true,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(80),
                'registration_deadline' => Carbon::now()->addDays(75),
            ],
            [
                'code' => 'STIN-INTEL-001',
                'title' => 'Tryout STIN - Sekolah Tinggi Intelijen Negara',
                'description' => 'Persiapan khusus tes masuk STIN dengan materi yang disesuaikan dengan karakteristik institusi intelijen.',
                'category' => 'kedinasan',
                'time_limit' => 200,
                'attempts_allowed' => 1,
                'price' => 120000.00,
                'is_active' => true,
                'is_free' => false,
                'show_result' => false,
                'randomize_questions' => true,
                'exam_date' => Carbon::now()->addDays(90),
                'registration_deadline' => Carbon::now()->addDays(85),
            ]
        ];

        foreach ($tests as $test) {
            Test::updateOrCreate(
                ['code' => $test['code']], // Find by code instead of slug
                $test // Update or create with this data
            );
        }
    }
}
